### ISSUE TITLE
Use references in molecule.yml instead of symlinks

### ISSUE THREAD

**Issue by andersharrisson-ess** [alvistack/ansible-collection-kubernetes#3]
Since Molecule supports referencing playbook paths, I think it makes more sense to use `provisioner.playbooks.$action` in molecule.yml to share Molecule playbooks across different scenarios than using symlinks.
```
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    prepare: ../default/prepare.yml
    verify: ../default/verify.yml
```
