### ISSUE TITLE
Comparing ansible_hostname with ansible_play_hosts can cause issues

### ISSUE THREAD

**Issue by andersharrisson-ess** [alvistack/ansible-collection-kubernetes#5]
At many places in the roles, there are comparisons like:
```when: ansible_hostname == ansible_play_hosts[0]```

This can cause issues in the situation where the inventory does not explicitly name the hosts in the inventory the same as what resolves to the hostname on the machine. For instance if you need to use the fqdn:
```
[all]
k8s-08.cslab.esss.lu.se
k8s-09.cslab.esss.lu.se
k8s-10.cslab.esss.lu.se
```

This can be worked around by setting ansible_host:
```
[all]
k8s-08 ansible_host=k8s-08.cslab.esss.lu.se
k8s-09 ansible_host=k8s-09.cslab.esss.lu.se
k8s-10 ansible_host=k8s-10.cslab.esss.lu.se
```

But I think it's wrong that the roles sets requirements for how the inventory should look. At least in some of the cases I think we can use `run_once` instead?

**Comment by aharrisson** [comment]
If run_once is not enough, the roles should at least use `inventory_hostname` instead of `ansible_hostname`.

**Comment by hswong3i** [comment]
Yes, `run_once` is not enough, e.g. first initialize the no.1 etcd/ceph/kubernetes master node, then copy files assets to the remaining master node and join the cluster. We need a way to figure out which is the first node and which are the remaining nodes.

BTW, switching from `ansible_hostname` to `inventory_hostname` is possible, but the main concern is: which once does `ansible_play_hosts` referencing? We need some simple test to confirm this.

**Comment by hswong3i** [comment]
@aharrisson Ok after research Ansible also use `inventory_hostname` with `ansible_play_hosts` internally, ( see https://github.com/ansible/ansible/blob/308723c3ca1122363e419070f1fa1d76ff5611a9/test/integration/targets/include_import/run_once/playbook.yml):

```
- hosts: testing
  gather_facts: false
  vars:
    lola: untouched
  tasks:
    - include_tasks: include_me.yml
      run_once: true

    - assert:
        that:
          - lola == 'wiseman'
      when: inventory_hostname == ansible_play_hosts[0]

    - assert:
        that:
          - lola == 'untouched'
      when: inventory_hostname != ansible_play_hosts[0]
```

I will update all roles accordingly ;-)
